title: FluMut documentation
description: Documentation for FluMut and FluMut-GUI
theme: just-the-docs

url: https://github.com/EdoardoGiussani/ghpages_test/FluMut

aux_links:
  FluMut Repository: https://github.com/EdoardoGiussani/ghpages_test
